export const INCREMENT_ENTHUSIASM = "INCREMENT_ENTHUSIASM";

export const DECREMENT_ENTHUSIASM = "DECREMENT_ENTHUSIASM";

export const GET_OPEN_API_CHOICES_SUCCESS = "GET_OPEN_API_CHOICES_SUCCESS";

export const GET_OPEN_API_CHOICES_FAILURE = "GET_OPEN_API_CHOICES_FAILURE";
